AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  A Kubernetes ValidatingWebhookConfiguration and serverless backend:
  Deny Pods with container images that don't meet your compliance requirements.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-ecr-repository-compliance-webhook
    Description: "A Kubernetes ValidatingWebhookConfiguration and serverless backend: Deny Pods with container images that don't meet your compliance requirements"
    Author: Simon Woldemichael
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["kubernetes", "validating", "admission", "webhook", "eks", "ecr"]
    HomePageUrl: https://github.com/aws-samples/amazon-ecr-repository-compliance-webhook
    SemanticVersion: 1.5.0
    SourceCodeUrl: https://github.com/aws-samples/amazon-ecr-repository-compliance-webhook

Parameters:
  ApiGwVpcEndpointId:
    Type: String
    Description: API Gateway VPC Endpoint ID
  RegistryRegion:
    Type: String
    Description: Optional. What AWS region should this Lambda function interact with ECR in?
    Default: ""
  RegistryId:
    Type: String
    Description: Optional. What AWS account should this Lambda function interact with ECR in?
    Default: ""

Conditions:
  HasRegistryRegion: !Not [!Equals [!Ref RegistryRegion, ""]]

Resources:
  ECRRepositoryComplianceWebhookExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ecr:DescribeRepositories
                  - ecr:DescribeImageScanFindings
                  - inspector2:ListCoverageStatistics
                  - inspector2:ListFindings
                  - inspector2:ListFindingAggregations
                  - inspector2:ListCoverage
                  - inspector2:GetFindingsReportStatus
                  - inspector:ListFindings
                  - inspector:DescribeFinding
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: ECRRepositoryComplianceWebhookLambdaPolicy

  ECRRepositoryComplianceWebhookRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ResourcePolicy:
          IntrinsicVpceWhitelist:
          - !Ref ApiGwVpcEndpointId
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds:
        - !Ref ApiGwVpcEndpointId

  ECRRepositoryComplianceWebhookFunction:
    Type: AWS::Serverless::Function
    Description: Lambda handler for amazon-ecr-repository-compliance-webhook
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: amazon-ecr-repository-compliance-webhook
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
      - arm64
      MemorySize: 128
      Role: !GetAtt ECRRepositoryComplianceWebhookExecutionRole.Arn
      Timeout: 15
      Environment:
        Variables:
          REGISTRY_REGION: !If [HasRegistryRegion, !Ref RegistryRegion, !Ref "AWS::NoValue"]
          REGISTRY_ID: !Ref RegistryId
      Events:
        ValidationEvent:
          Type: Api
          Properties:
            Path: /check-image-compliance
            Method: post
            RestApiId: !Ref ECRRepositoryComplianceWebhookRestApi

  ConfigAPIGatewayLambdaInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ECRRepositoryComplianceWebhookFunction
      Principal: apigateway.amazonaws.com

Outputs:
  WebhookURL:
    Description: "ValidatingWebhookConfiguration invocation URL"
    Value: !Sub "https://${ECRRepositoryComplianceWebhookRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/check-image-compliance"
