apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2020-12-18T00:00:05Z"
  labels:
    amazon-ecr-repository-compliance-webhook: enabled
  name: testing-the-gods-admission
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048
  namespace: testing-the-gods-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
      - image: 168134825737.dkr.ecr.us-west-2.amazonaws.com/docker-2048:latest #alexwhen/docker-2048
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80
          protocol: TCP
