apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: admission-webhook/webhook-proxy-cert
  name: amazon-ecr-repository-compliance-webhook-config
  labels:
    app: amazon-ecr-repository-compliance-webhook
webhooks:
  - name: admission.ecr.amazonaws.com
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 8
    failurePolicy: Fail
    clientConfig:
      service:
        name: webhook-proxy
        namespace: admission-webhook
        path: /check-image-compliance
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    namespaceSelector: # Optionally add a namespaceSelector and matchLabels
      matchLabels:
        amazon-ecr-repository-compliance-webhook: enabled
