---
apiVersion: v1
kind: Namespace
metadata:
  name: admission-webhook
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-conf
  namespace: admission-webhook
data:
  proxy.conf: |-
    server {
      listen 8443 ssl;
      ssl_certificate      bitnami/certs/tls.crt;
      ssl_certificate_key  bitnami/certs/tls.key;

      location /check-image-compliance {
        proxy_pass <replace-with-api-gw-endpoint>;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-proxy
  namespace: admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhook-proxy
    spec:
      containers:
      - image: public.ecr.aws/bitnami/nginx:1.27.0
        name: webhook-proxy
        ports:
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: proxy-config
          mountPath: /opt/bitnami/nginx/conf/server_blocks/
        - name: cert
          mountPath: /opt/bitnami/nginx/conf/bitnami/certs
          readOnly: true
      volumes:
      - name: proxy-config
        configMap:
          name: proxy-conf
      - name: cert
        secret:
          defaultMode: 420
          secretName: admission-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-proxy
  namespace: admission-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/name: webhook-proxy
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-proxy-cert
  namespace: admission-webhook
spec:
  dnsNames:
  - webhook-proxy.admission-webhook.svc
  - webhook-proxy.admission-webhook.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: webhook-proxy-issuer
  secretName: admission-webhook-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-proxy-issuer
  namespace: admission-webhook
spec:
  selfSigned: {}
